[2024-08-08 08:05:59,143] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dota_dag.extract_heroes 2024-08-08T08:00:56.986609+00:00 [queued]>
[2024-08-08 08:05:59,156] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: dota_dag.extract_heroes 2024-08-08T08:00:56.986609+00:00 [queued]>
[2024-08-08 08:05:59,156] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2024-08-08 08:05:59,157] {taskinstance.py:1069} INFO - Starting attempt 2 of 2
[2024-08-08 08:05:59,157] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2024-08-08 08:05:59,174] {taskinstance.py:1089} INFO - Executing <Task(PythonOperator): extract_heroes> on 2024-08-08T08:00:56.986609+00:00
[2024-08-08 08:05:59,178] {standard_task_runner.py:52} INFO - Started process 67 to run task
[2024-08-08 08:05:59,183] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'dota_dag', 'extract_heroes', '2024-08-08T08:00:56.986609+00:00', '--job-id', '12', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/dota.py', '--cfg-path', '/tmp/tmpk9uxvb86', '--error-file', '/tmp/tmp_pdhbf90']
[2024-08-08 08:05:59,183] {standard_task_runner.py:77} INFO - Job 12: Subtask extract_heroes
[2024-08-08 08:05:59,231] {logging_mixin.py:104} INFO - Running <TaskInstance: dota_dag.extract_heroes 2024-08-08T08:00:56.986609+00:00 [running]> on host ec67c4f7e31a
[2024-08-08 08:05:59,269] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=dota_dag
AIRFLOW_CTX_TASK_ID=extract_heroes
AIRFLOW_CTX_EXECUTION_DATE=2024-08-08T08:00:56.986609+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-08-08T08:00:56.986609+00:00
[2024-08-08 08:05:59,302] {python.py:118} INFO - Done. Returned value was: None
[2024-08-08 08:05:59,314] {taskinstance.py:1192} INFO - Marking task as SUCCESS. dag_id=dota_dag, task_id=extract_heroes, execution_date=20240808T080056, start_date=20240808T080559, end_date=20240808T080559
[2024-08-08 08:05:59,348] {taskinstance.py:1246} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-08 08:05:59,393] {local_task_job.py:146} INFO - Task exited with return code 0
